### ISSUE TITLE
Airspace Base Input Format

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/sector-file-compiler#137]
Airspace_Bases.txt in airports gets read in in a special format, but gets outputted as freetext. We need to handle this.

**Comment by GeekPro101** [comment]
As per my comment [here](https://github.com/VATSIM-UK/UK-Sector-File/pull/3538#issuecomment-812900119), I think the best way to go forward is just to correct the source files rather than continuing to have the compiler make changes. 
We coulld possibly have the compiler insert the 'EGBB Airspace Bases' bit,  but I'm not too fussed.

**Comment by AndyTWF** [comment]
Source files corrected and PR opened over at UKSF.
