### ISSUE TITLE
Sector lines should be closed

### ISSUE THREAD

**Issue by GeekPro101** [VATSIM-UK/sector-file-compiler#166]
Sectors (e.g SECTORLINEs used by Ownership files in BORDERS) should be closed - i.e. they form a continuous line, and the last coordinate should join to the first.

This is actually something ES does detect, and gives a 'Not closed border lines (sector name)' error.

An example of this can be found in [this issue](https://github.com/VATSIM-UK/UK-Sector-File/issues/3953) and [related PR](https://github.com/VATSIM-UK/UK-Sector-File/pull/3954)

It would be really cool if the compiler could check this and generate a compile-time error.

**Comment by GeekPro101** [comment]
Closed by #169

**Comment by hsugden** [comment]
Interestingly, a lot of the non-contiguous border definitions identified by the latest compiler versions didn't actually involve adding new/different lines to the definition, but rather just swapping lines around. It turns out that EuroScope doesn't actually care for the ordering of the lines included in the 'BORDER' list, only that all of the lines included should link up _somewhere_.

So even if the actual polygon is made up by Line 1, which connects to Line 2, which connects to Line 3, which connects to Line 4 (which also connects to 1)...

`Line 4:Line 2:Line 3:Line 1` wouldn't throw up an error in EuroScope!

I had no idea this was the case 🤯
